name: build

on: [push]

jobs:
  build-ubuntu:
    needs: format

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install sfml
      run: apt install sfml-dev

    - name: build
      run: make