name: ci

on: [push]

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: '.'
        extensions: 'hpp,cpp'
        clangFormatVersion: 9
        style: Google

  build-ubuntu:    
    needs: check-format

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install sfml
      run: sudo apt install libsfml-dev

    - name: build
      run: make
      
  build-windows:    
    needs: check-format

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: install sfml
      run: 
        wget https://artifacts.sfml-dev.org/by-branch/master/windows-gcc-730-mingw-32.zip
        unzip windows-gcc-730-mingw-32.zip >> %LIBRARY_PATH%

    - name: build
      run: make
