name: ci

on: [push]

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: '.'
        extensions: 'hpp,cpp'
        clangFormatVersion: 9
        style: Google

  build-ubuntu:    
    needs: format

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install sfml
      run: apt install sfml-dev

    - name: build
      run: make